#!/usr/bin/perl
open (my $inputfile, "<", 'cdhit_clstr_sorted.txt') || die "\n   Cannot open the specified file. Please double check your file name and path.\n\n";
    open(my $fh, '>', 'report.txt');
    while (<$inputfile>)
{
print $fh "My first report generated by perl\n";
$TotalClusters=`grep -c '>Cluster' cdhit_clstr_sorted.txt`;
for($i=0;$i<$TotalClusters;$i++)
{
$j=$i+1;
$lines=`perl -e 'while (<>){print if (/^>Cluster $i/../^>Cluster $j/);}' cdhit_clstr_sorted.txt | wc -l`;
$linesExcludingPattern=$lines-2;
print $fh "Cluster $i has $linesExcludingPattern sequences\n";
}

    close $fh;
    close $inputfile;
}


